### Lấy danh sách bài viết
GET http://localhost/api/comment-list

### Tìm kiếm bài viết
GET http://localhost/api/comment-search
Content-Type: application/json

### Lấy bài viết chi tiết
GET http://localhost/api/comment-detail

### Thêm bài viết mới
PUT http://localhost/api/comment-new
Content-Type: application/json

{
    "title": "Bai viet 1",
    "content": "Nội dung bài viết 1"
}

### Chỉnh sửa bài viết
POST http://localhost/api/comment-edit
Content-Type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}
