### Lấy danh sách bài viết
GET http://localhost/api/posts

### Lấy bài viết chi tiết
GET http://localhost/api/post

### Tìm kiếm bài viết
GET http://localhost/api/post-search
Content-Type: application/json

### Thêm bài viết mới
PUT http://localhost/api/post-new
Content-Type: application/json

{
    "title": "Thám Tử Lừng Danh Conan",
    "content": "Vụ Án Tại Nhà Hàng Trung Hoa",
    "user": "656614e6674e555be1a0a2ba"
}

### Chỉnh sửa bài viết
POST http://localhost/api/post-edit
Content-Type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}
